-- MIT license
-- (c) Illinois_Roadbuff "Rogue Jr"
-- Usage: ./src/outside-scope.luau

local WARNING = [[
    This Git repository does NOT hold the true source code for "The Plains" and only holds place files, thereby 
    being incompatible with package managers.

    Separating "source code" for this project does not make sense since standalone repositories are already
    available for some of the scripts, AND one could already access the scripts from the place file. The place file
    also contains parts, meshes, unions, etc. that is not necesarilly considered "source code."

    Maintaining the separate "source code" per release would be a nightmare and a waste of time, in my opinion.

    Get the place file here:
        Codeberg (main): https://codeberg.org/project-roadwork/the-plains 
        GitHub (backup/mirrored): https://github.com/project-roadwork/the-plains  
]]

warn(WARNING)